### ISSUE TITLE
Untrusted repository

### ISSUE THREAD

**Issue by lvanvugt** [fluxxus-nl/ATDD.TestScriptor#13]
Running Install-Module ATDD.TestScriptor gives following "error".

> Untrusted repository
> You are installing the modules from an untrusted repository. If you trust this repository, change its
> InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
> 'PSGallery'?
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"):

Is this expected?

**Comment by jhoek** [comment]
Yes. Either allow installation from the PowerShell gallery on a case-by-case basis (which I would recommend), or mark it as a trusted repository. Will add this to the README.
