### ISSUE TITLE
Scenario tag is not created fully right

### ISSUE THREAD

**Issue by lvanvugt** [fluxxus-nl/ATDD.TestScriptor#16]
```
Feature 'Another Feature' {
    Scenario 1 'Oink' {
        Given Boink
        When Kloink
        Then Zoink
    }
}
```

leads to the following .al code:

```
    [Test]
    procedure Oink()
    // [FEATURE] Another Feature
    begin
        // [SCENARIO] 1 Oink
        Initialize();
        // [GIVEN] Boink
        Boink();
       // [WHEN] Kloink
        Kloink();
        // [THEN] Zoink
        Zoink();
    end;
```
This should
```

    [Test]
    procedure Oink()
    // [FEATURE] Another Feature
    begin
        // [SCENARIO #1] Oink
        Initialize();
        // [GIVEN] Boink
        Boink();
        // [WHEN] Kloink
        Kloink();
        // [THEN] Zoink
        Zoink();
    end;
```
Note that I removed the empty lines in the code.

**Comment by jhoek** [comment]
[SCENARIO #1] (like above) or [SCENARIO #0001] (like in the sample codeunit)?

**Comment by lvanvugt** [comment]
> [SCENARIO #1] (like above) or [SCENARIO #1] (like in the sample codeunit)?

Spot the diference? I don't see it, so my answer would be: both.

**Comment by jhoek** [comment]
Argh! GitHub's MarkDown processing is a bit too clever! :-) Have just corrected my initial question.

**Comment by lvanvugt** [comment]
`[SCENARIO #0001]`

**Comment by jhoek** [comment]
Published as version 0.0.5 in the PowerShell Gallery.

**Comment by lvanvugt** [comment]
How can I see if Install-Module ATDD.TestScriptor has installed the newest version?

I am asking as it seems that either 0.0.4. is still installed or 0.0.5 still contains the bug.

**Comment by lvanvugt** [comment]
OK, fikxed it by closing the ISE and reinstall the module.

So the bug is fixed.

 ```
   [Test]
    procedure Oink()
    // [FEATURE] Another Feature
    begin
        // [SCENARIO #0001] Oink
        Initialize();
        // [GIVEN] Boink
        Boink();
        // [WHEN] Kloink
        Kloink();
        // [THEN] Zoink
        Zoink();
    end;

```

**Comment by jhoek** [comment]
Get-Module ATDD.TestScriptor -ListAvailable | Format-List gives you all the information. Perhaps a forced (`-Force`) module import could help, but restarting your PowerShell session is much safer/quicker! :-)
