### ISSUE TITLE
[GIVEN] should yield a creator method

### ISSUE THREAD

**Issue by lvanvugt** [fluxxus-nl/ATDD.TestScriptor#17]
When converting the [GIVEN} into code this should yield a creator method.

Example (removed part of no importance to the isseu)
   ```
 Scenario 1 'Check that label can be assigned to customer' {
	    Given	'A label'
	    Given	'A customer'
    }
```
Now yields .al code:
```
[Test]
procedure CheckThatLabelCanBeAssignedToCustomer()
// [FEATURE] LookupValue UT Customer
begin
    // [SCENARIO #0001] Check that label can be assigned to customer
    Initialize();
   
    // [GIVEN] A label
    ALabel();
    
    // [GIVEN] A customer
    ACustomer();
end;
```
The following would be preferable:
```
[Test]
procedure CheckThatLabelCanBeAssignedToCustomer()
// [FEATURE] LookupValue UT Customer
begin
    // [SCENARIO #0001] Check that label can be assigned to customer
    Initialize();
   
    // [GIVEN] A label
    CreateLabel();
    
    // [GIVEN] A customer
    CreateCustomer();
end;
```
If we do not want this to be too imposing we could consider this an option for the ConvertTo-ALTestCodeunit commandlet.

**Comment by jhoek** [comment]
@lvanvugt I think this assumes that the description for Given is in English? Otherwise, how would we know to replace "A " with "Create"? Maybe the conversion cmdlet should have user-overridable scriptblocks for these things, so that we can implement the ENU logic, but users can provide other implementations if they prefer?

**Comment by lvanvugt** [comment]
Good question, Jan. ANd I think (if I understand you question well enough) my answer is YES.

BTW: I could live with leaving the 'A' so it would so that

`// [GIVEN] A label`

yields

`CreateALabel();`
