### ISSUE TITLE
How to append new scenarios to existing test codeunit

### ISSUE THREAD

**Issue by lvanvugt** [fluxxus-nl/ATDD.TestScriptor#19]
Is there a way to make ConvertTo-ALTestCodeunit ... | Out-File ... append newly added scenarios to an existing test codeunit?

Or is it just copy and paste?

**Comment by jhoek** [comment]
For now, I would say copy/paste, or regenerate the codeunit including the new scenarios? But I guess you're talking about situations where the developer has already started "filling in the blanks"?

**Comment by lvanvugt** [comment]
>  But I guess you're talking about situations where the developer has already started "filling in the blanks"?
Indeed.

**Comment by jhoek** [comment]
I don't have an instant solution, but I'm open to any suggestions! :-)

**Comment by lvanvugt** [comment]
I recon you are ;-)

Let's leave it for now. Will close. Might pick up in future.
